name: BDD Feature Tests

on: 
  push:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List feature tests folder for debug
        run: ls -l cypress/e2e/feature_tests/

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Allure enabled
        run: npx cypress run --spec cypress/e2e/feature_tests/*.feature --env allure=true

      - name: Check allure-results folder contents
        run: ls -laR allure-results || echo "No allure-results folder found"

      - name: Generate Allure HTML report
        run: |
          cd cypress_extended_tests_and_utilities
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure

      - name: Check generated allure report folder contents
        run: ls -laR allure || echo "No allure report generated"

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress_extended_tests_and_utilities/allure

