name: BDD Feature Tests

on: 
  push:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Feature tests with Allure enabled
        env:
            CYPRESS_GOREST_PRIMARY_TOKEN: ${{secrets.GOREST_PRIMARY_TOKEN}}
        run: npx cypress run --spec cypress/e2e/feature_tests/*.feature --env allure=true

# Checkout existing gh-pages content to fetch historical Allure data
      - name: Checkout gh-pages for Allure history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: old-report

# Copy history into allure-results (ignore errors if missing)
      - name: Restore Allure history
        run: |
          mkdir -p allure-results/history
          cp -r old-report/bdd_feature_report/* allure-results/history/ || true


      - name: Generate Allure HTML report for Feature Tests 
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure

      - name: Deploy Allure Report to GitHub Pages at "bdd-feature-report"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure
          destination_dir: bdd_feature_report