name: BDD Feature Tests
on: 
    push:
    workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Reporsitory
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies
        run: npm install

      - name: Clear Allure Test Execution Report History
        run: npm run allure:clear
        
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.1.0
        with:
         install: false 
         command: npx cypress run --spec cypress/e2e/feature_tests/*.feature --env allure=true
        continue-on-error: true  
        
      - name: Debug Check allure-results directory
        run: |
          echo "=== Contents of allure-results/ ==="
          ls -l allure-results || echo "No allure-results found"
          echo "==================================="

      - name: Preserve Allure history
        run: |
                npm run allure:history

      - name: Clear Allure History
        if: always()
        run: |
                npm install -g allure-commandline
                npm run allure:clear
                npm run allure:report



      - name: Debug - check generated allure report
        run: ls -laR allure || echo "allure report not generated"

      - name: Deploy Data Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./allure
             keep_files: true

